config/routes.rb
Rails.application.routes.draw do

  devise_for :customers
  devise_for :commercials
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  #get '/contact', to: redirect('/instituts', status: 301) #Test redirection
  get "/fr/instituts-bio", to: redirect('/fr/instituts-beaute', status: 301)
  get "/fr/instituts-de-beaute-bio", to: redirect('/fr/instituts-beaute', status: 301)
  get "/fr/instituts-beaute-bio", to: redirect('/fr/instituts-beaute', status: 301)

  get "/fr/instituts-beaute-bio/nature-creative", to: redirect('/fr/instituts-beaute/nature-creative', status: 301)
  get "/fr/instituts-beaute-bio/rita-esthetique", to: redirect('/fr/instituts-beaute/rita-esthetique', status: 301)
  get "/fr/instituts-beaute-bio/liesse-beaute", to: redirect('/fr/instituts-beaute/liesse-beaute', status: 301)
  get "/fr/instituts-beaute-bio/le-clos-des-sources", to: redirect('/fr/instituts-beaute/le-clos-des-sources', status: 301)
  get "/fr/instituts-beaute-bio/ali-s-heaven-institut", to: redirect('/fr/instituts-beaute/ali-s-heaven-institut', status: 301)
  get "/fr/instituts-beaute-bio/zen-ment-belle", to: redirect('/fr/instituts-beaute/zen-ment-belle', status: 301)
  get "/fr/instituts-beaute-bio/liesse-beaute", to: redirect('/fr/instituts-beaute/liesse-beaute', status: 301)


  #get '/fr/contact', to: redirect('/fr/instituts-beaute', status: 302)
  # Defines the root path route ("/")
  scope "(:locale)", locale: /fr/ do
    root to: "pages#home"
    get "contact", to: "pages#contact"
    get "envoye", to: "pages#send_contact"
    get "formations", to: "pages#formations"
    get "donnees-personnelles",to: "pages#donnees"
    get "politique-confidentialite",to: "pages#confidentialite"
    get "gestion-cookies",to: "pages#cookies"
    get "mentions-legales",to:"pages#mentions"
    get "devenir-partenaire",to:"pages#devenir_partenaire"
    get "/instituts-beaute/region/:region", to: "pages#region", as: :region
    get :send_partenaire, to:"pages#send_partenaire",path:"send_partenaire"



    resources :espace_pro, path: "/espace-pro" do
      member do
        get "etablissements", to: "espace_pro#etablissements"
        get "cours-formations", to: "espace_pro#cours"
        get "commandes",to: "espace_pro#commandes"
        get "rendez-vous", to:"espace_pro#rdv"
        get "statistiques",to:"espace_pro#statistiques"
        get "edit_profile", to: "espace_pro#edit_profile"
        patch "update_profile", to: "espace_pro#update_profile"
        resources :custom_soins, only: [:index,:new,:create,:edit,:update,:destroy], path:"soins-personnalises"
        resources :cartes, only: [:new,:create,:show,:destroy]
        resources :stock_instituts, only: [:index,:edit,:update], path: "stock"
        resources :courses, only: [:index, :show]
        resources :carte_cadeaus, only: [:index,:show,:new,:create,:destroy], path: "cheques-cadeau"
        get :send_cheque, to: "carte_cadeaus#send_cheque"
        get :update_status, to: "espace_pro#update_status"
        #get :note_to_message, to: "espace_pro#note_to_message"
        post :addnote, to: "espace_pro#addnote"
        get "mediatheque",to: "espace_pro#phototheque"
        get :mediatheque_folder,to: "espace_pro#phototheque_folder", path:"/mediatheque/folders/:folder_id"
      end
      collection do
        get "produits", to: "espace_pro#produits"
        get "faq",to:"espace_pro#faq"
        get :institut, to: "espace_pro#institut_show", path: "/etablissements/:id"
        get :edit_institut, to: "espace_pro#edit_institut", path: "/etablissements/:id/edit"
        patch :update_institut, to: "espace_pro#update_institut"
        get "delete_photo", to: "espace_pro#delete_photo"
        get "delete_promo", to: "espace_pro#delete_promo"
        get "soins",to:"espace_pro#soins"
      end
    end

    resources :profiles

    resources :blog_posts, only: [:index,:show], path:"blog"

    resources :products, path: "cosmetiques" do
      member do
        get "delete_photo"
      end
      collection do
        #get "/filtres", to: "products#filtres",as: :cosmetique_filtres
        get "click-and-collect",to: "products#click_and_collect", as: :click_collect
        get :besoin, to: "products#type_besoin", path: "/preoccupation/:besoin"
        get :type_product, to: "products#type_product", path: "/type-produit/:type_product"
      end
    end
    #get "/corps", to: "products#category", as: :cosmetique_corps
    resources :soins do
      collection do
        get :visage
        get :corps
        get :massages
        get "cat_bis", to: "soins#cat_bis"
        get :reserver, to: "soins#reservation", path: "/reserver/:soin"
      end
    end
    post "soins/filter", to: "soins#filter"


    scope '/admin' do
      resources :team_members
      resources :prospects
      resources :courses, only: [:new,:create,:edit,:update,:destroy]
      resources :blog_posts, only: [:new,:create,:edit,:update,:destroy]
      get :all_posts, to: "admin#all_posts"
      resources :chapters, only: [:new,:create,:edit,:update,:destroy]
      get "/soins", to: "admin#admin_soins", as: :admin_soins
      get :clients, to: "admin#customers", path: "/clients"
      get :client, to: "admin#customer", path: "/clients/:id"
      get "/tous-les-cours", to: "admin#cours"
      get :instituts, to: "admin#instituts", as: :admin_instituts
      get :preview, to: "courses#preview", path: "/courses/:id/preview"
      get :edit_home_content, to: "admin#edit_home_content"
      post :update_home_content, to: "admin#update_home_content"

      get 'mediatheque', to: "phototheque_espace_pros#index"
      get 'mediatheque/add_file', to: "phototheque_espace_pros#add_file"
      patch 'mediatheque/save_file', to: "phototheque_espace_pros#save_file"
      get :delete_file, to: "phototheque_espace_pros#delete_file", path: "mediatheque/:id/delete"

      resources :phototheque_espace_pro_folders, only: [:new,:create,:show,:edit,:update,:destroy],path: "mediatheque/folders"
      get :mediateque_folder_add_file, to: "phototheque_espace_pro_folders#add_file", path: 'mediatheque/folders/:id/add_file'
      patch 'mediatheque/folders/:id/save_file', to: "phototheque_espace_pro_folders#save_file"
      get :mediateque_folder_delete_file, to: "phototheque_espace_pro_folders#delete_file", path: "mediatheque/folders/:id/delete"
      resources :slider_homes, only: [:index] do
        resources :slide_items, only: [:new,:create,:edit,:update,:destroy]
      end

    end

    resources :admin

    resources :crm do
      collection do
        get :prospects, to: 'crm#crm_prospects', path: ":id/prospects"
        get :show_prospect, :path => "show", path: "prospect/:id"
        get :new_prospect,to: 'crm#new_prospect', :path => "/new"
        get :edit_prospect, :path => "prospect/:id/edit"
        get :clients, to: "crm#crm_customers", path: ":id/clients"
        get :customer, to: "crm#show_customer", path: "/client/:id"
        get :new_customer, to: "crm#new_customer"
        get :edit_customer, to: "crm#edit_customer", path: "/client/:id/edit"

        get :instituts, to: "crm#instituts", path: "instituts"
        get :new_institut, to: "crm#new_institut"
        get :edit_institut, to: "crm#edit_institut", path: "instituts/:id/edit"
        post :create_institut, to: "crm#create_institut"

        get "delete_photo", to: "crm#delete_photo"
        get :statistiques, to: "crm#statistiques", path: ":id/statistiques"

        get :filter_up, to: "crm#filter_up"
        get :filter_down, to: "crm#filter_down"

        post :create_customer, to: "crm#create_customer"
        post :create_prospect, to: "crm#create_prospect"

        get :prospection, to: "crm#prospection"
        get :request_prospection, to: "crm#request_prospection"

        resources :orders

      end
      member do
        patch :update_prospect
        patch :update_customer, to: "crm#update_customer"
        patch :update_institut, to: "crm#update_institut"

        #get :prospects, to: 'crm#crm_prospects'
        #get :edit_prospect, :path => "edit"
        #patch :update_prospect
        #get :show_prospect, :path => "show"
        #get :clients, to: "crm#crm_customers"
        #get :new_customer, to: "crm#new_customer"
        #post :create_customer, to: "crm#create_customer"
        #get :new_institut, to: "crm#new_institut"
        ##get "/client", to: "crm#show_customer"
      end
    end




    resources :instituts, path:"instituts-beaute" do
      collection do
        get :send_contact, path:"send"
        get "/:region/:lieu", to: "instituts#lieu", as: :ville
        get "/villes",to: "instituts#villes", as: :all_villes
      end
    end

    get "/:category", to: "products#categories", as: :cosmetique_category
    post "/:category/filter", to: "products#filter", as: :filter_category

    #get "instituts-beaute/:region/:lieu", to: "instituts#lieu", as: :ville

  end
end

app/views/admin/admin_soins.html.erb
<h1>Admin soins</h1>
<ul>
  <% @soins.each do |soin| %>
    <li>
      <%= link_to soin.name, edit_soin_path(soin) %>
    </li>
  <% end %>
</ul>

app/views/admin/all_posts.html.erb
<h1>All posts</h1>
<ul>
<% @posts.each do |post| %>
<li><%= link_to post.titre, edit_blog_post_path(post) %></li>
<% end %>
</ul>

app/views/admin/cours.html.erb
<h1>Cours</h1>
<ul>
  <% @cours.each do |cours| %>
    <li>
    <%= link_to cours.titre, preview_path(cours)%>
    <%= link_to "Editer", edit_course_path(cours) %>
    </li>
  <% end %>
</ul>

app/views/admin/create.html.erb
<h1>Admin#create</h1>
<p>Find me in app/views/admin/create.html.erb</p>

app/views/admin/customer.html.erb
<h1>Client - <%= @customer.lastname%> <%= @customer.firstname %></h1>

app/views/admin/customers.html.erb
<h1>Clients</h1>
<ul>
<% @customers.each do |client| %>
  <li>
    <p><%= client.lastname %></p>
    <%= link_to "voir fiche client", client_path(client) %>
  </li>
<% end %>
</ul>

app/views/admin/destroy.html.erb
<h1>Admin#destroy</h1>
<p>Find me in app/views/admin/destroy.html.erb</p>

app/views/admin/edit.html.erb
<h1>Admin#edit</h1>
<p>Find me in app/views/admin/edit.html.erb</p>

app/views/admin/edit_home_content.html.erb
<h1>Modifier les avis de la home</h1>
<div class="custom_form">
<table>
  <thead>
    <tr>
      <th>Auteur</th>
      <th>Commentaire</th>
      <th>Note</th>
    </tr>
  </thead>
  <tbody>
  <% @reviews.each do |review| %>
    <tr>
      <%= form_with url: update_home_content_path, method: :post do |f| %>
        <%= f.hidden_field :content_type, value: "avis_home"%>
        <%= f.hidden_field :key, value: review.first%>
        <td><%= review.first %></td>
        <td><%= f.label "Avis" %>
        <%= f.text_field :new_review, value: review[1]["review"] %></td>
        <td><%= f.label "Note" %>
        <%= f.text_field :new_note, value: review[1]["note"] %></td>
        <td><%= f.submit "Mettre à jour l'avis" %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

<h2>Choix des instituts partenaires à afficher sur la page d'accueil</h2>
<% @instituts_partenaires.each do |institut| %>
  <%= form_with url: update_home_content_path, method: :post do |f| %>

          <%= f.hidden_field :content_type, value: "partenaires"%>
          <%= f.hidden_field :item_number, value: institut[0] %>
          <% if Institut.all.ids.include?(institut[1]["id"])  %>
            <%= f.collection_select :institut_selected, Institut.all, :id, :name, { prompt: Institut.find(institut[1]["id"]).name } %>
          <% else %>
            <%= f.collection_select :institut_selected, Institut.all, :id, :name, { prompt: "Selectionnez un institut"} %>
          <% end %>
          <%= f.submit "Choisir cet institut" %></>
  <% end %>
<% end %>

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>


<%= link_to "Ajouter un prosect", new_prospect_path %>
<%= link_to "Voir tous les prospects", prospects_path %>
<%= link_to "voir les soins", admin_soins_path %>
<%= link_to "instituts", admin_instituts_path %>
<%= link_to "Les cours", tous_les_cours_path %>
<%= link_to "Créer un article de blog", new_blog_post_path %>
<%= link_to "All posts", all_posts_path %>
<%= link_to "Editer contenus de la home",edit_home_content_path %>
<%= link_to "Voir slides/slider", slider_homes_path %>

<%= link_to "Accéder à la mediathèque", mediatheque_path %>
<hr>
<%= button_to(
        "Log Out",
        destroy_user_session_path,
        method: :delete
      ) %>

app/views/admin/instituts.html.erb
<h1>Instituts</h1>
<ul>
  <% @instituts_views.each do |stat| %>
    <% if stat.first != nil %>
      <% x =  stat[1].group_by { |elmt| elmt.time.to_date } %>
      <li><%= stat.first %> | <%= stat[1].size %> vues</li>
    <% end %>
  <% end %>
</ul>

app/views/admin/new.html.erb
<h1>Admin#new</h1>
<p>Find me in app/views/admin/new.html.erb</p>

app/views/admin/show.html.erb
<h1>Admin#show</h1>
<p>Find me in app/views/admin/show.html.erb</p>

app/views/admin/update.html.erb
<h1>Admin#update</h1>
<p>Find me in app/views/admin/update.html.erb</p>