config/routes.rb
Rails.application.routes.draw do

  devise_for :customers
  devise_for :commercials
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  #get '/contact', to: redirect('/instituts', status: 301) #Test redirection
  get "/fr/instituts-bio", to: redirect('/fr/instituts-beaute', status: 301)
  get "/fr/instituts-de-beaute-bio", to: redirect('/fr/instituts-beaute', status: 301)
  get "/fr/instituts-beaute-bio", to: redirect('/fr/instituts-beaute', status: 301)

  get "/fr/instituts-beaute-bio/nature-creative", to: redirect('/fr/instituts-beaute/nature-creative', status: 301)
  get "/fr/instituts-beaute-bio/rita-esthetique", to: redirect('/fr/instituts-beaute/rita-esthetique', status: 301)
  get "/fr/instituts-beaute-bio/liesse-beaute", to: redirect('/fr/instituts-beaute/liesse-beaute', status: 301)
  get "/fr/instituts-beaute-bio/le-clos-des-sources", to: redirect('/fr/instituts-beaute/le-clos-des-sources', status: 301)
  get "/fr/instituts-beaute-bio/ali-s-heaven-institut", to: redirect('/fr/instituts-beaute/ali-s-heaven-institut', status: 301)
  get "/fr/instituts-beaute-bio/zen-ment-belle", to: redirect('/fr/instituts-beaute/zen-ment-belle', status: 301)
  get "/fr/instituts-beaute-bio/liesse-beaute", to: redirect('/fr/instituts-beaute/liesse-beaute', status: 301)


  #get '/fr/contact', to: redirect('/fr/instituts-beaute', status: 302)
  # Defines the root path route ("/")
  scope "(:locale)", locale: /fr/ do
    root to: "pages#home"
    get "contact", to: "pages#contact"
    get "envoye", to: "pages#send_contact"
    get "formations", to: "pages#formations"
    get "donnees-personnelles",to: "pages#donnees"
    get "politique-confidentialite",to: "pages#confidentialite"
    get "gestion-cookies",to: "pages#cookies"
    get "mentions-legales",to:"pages#mentions"
    get "devenir-partenaire",to:"pages#devenir_partenaire"
    get "/instituts-beaute/region/:region", to: "pages#region", as: :region
    get :send_partenaire, to:"pages#send_partenaire",path:"send_partenaire"



    resources :espace_pro, path: "/espace-pro" do
      member do
        get "etablissements", to: "espace_pro#etablissements"
        get "cours-formations", to: "espace_pro#cours"
        get "commandes",to: "espace_pro#commandes"
        get "rendez-vous", to:"espace_pro#rdv"
        get "statistiques",to:"espace_pro#statistiques"
        get "edit_profile", to: "espace_pro#edit_profile"
        patch "update_profile", to: "espace_pro#update_profile"
        resources :custom_soins, only: [:index,:new,:create,:edit,:update,:destroy], path:"soins-personnalises"
        resources :cartes, only: [:new,:create,:show,:destroy]
        resources :stock_instituts, only: [:index,:edit,:update], path: "stock"
        resources :courses, only: [:index, :show]
        resources :carte_cadeaus, only: [:index,:show,:new,:create,:destroy], path: "cheques-cadeau"
        get :send_cheque, to: "carte_cadeaus#send_cheque"
        get :update_status, to: "espace_pro#update_status"
        #get :note_to_message, to: "espace_pro#note_to_message"
        post :addnote, to: "espace_pro#addnote"
        get "mediatheque",to: "espace_pro#phototheque"
        get :mediatheque_folder,to: "espace_pro#phototheque_folder", path:"/mediatheque/folders/:folder_id"
      end
      collection do
        get "produits", to: "espace_pro#produits"
        get "faq",to:"espace_pro#faq"
        get :institut, to: "espace_pro#institut_show", path: "/etablissements/:id"
        get :edit_institut, to: "espace_pro#edit_institut", path: "/etablissements/:id/edit"
        patch :update_institut, to: "espace_pro#update_institut"
        get "delete_photo", to: "espace_pro#delete_photo"
        get "delete_promo", to: "espace_pro#delete_promo"
        get "soins",to:"espace_pro#soins"
      end
    end

    resources :profiles

    resources :blog_posts, only: [:index,:show], path:"blog"

    resources :products, path: "cosmetiques" do
      member do
        get "delete_photo"
      end
      collection do
        #get "/filtres", to: "products#filtres",as: :cosmetique_filtres
        get "click-and-collect",to: "products#click_and_collect", as: :click_collect
        get :besoin, to: "products#type_besoin", path: "/preoccupation/:besoin"
        get :type_product, to: "products#type_product", path: "/type-produit/:type_product"
      end
    end
    #get "/corps", to: "products#category", as: :cosmetique_corps
    resources :soins do
      collection do
        get :visage
        get :corps
        get :massages
        get "cat_bis", to: "soins#cat_bis"
        get :reserver, to: "soins#reservation", path: "/reserver/:soin"
      end
    end
    post "soins/filter", to: "soins#filter"


    scope '/admin' do
      resources :team_members
      resources :prospects
      resources :courses, only: [:new,:create,:edit,:update,:destroy]
      resources :blog_posts, only: [:new,:create,:edit,:update,:destroy]
      get :all_posts, to: "admin#all_posts"
      resources :chapters, only: [:new,:create,:edit,:update,:destroy]
      get "/soins", to: "admin#admin_soins", as: :admin_soins
      get :clients, to: "admin#customers", path: "/clients"
      get :client, to: "admin#customer", path: "/clients/:id"
      get "/tous-les-cours", to: "admin#cours"
      get :instituts, to: "admin#instituts", as: :admin_instituts
      get :preview, to: "courses#preview", path: "/courses/:id/preview"
      get :edit_home_content, to: "admin#edit_home_content"
      post :update_home_content, to: "admin#update_home_content"

      get 'mediatheque', to: "phototheque_espace_pros#index"
      get 'mediatheque/add_file', to: "phototheque_espace_pros#add_file"
      patch 'mediatheque/save_file', to: "phototheque_espace_pros#save_file"
      get :delete_file, to: "phototheque_espace_pros#delete_file", path: "mediatheque/:id/delete"

      resources :phototheque_espace_pro_folders, only: [:new,:create,:show,:edit,:update,:destroy],path: "mediatheque/folders"
      get :mediateque_folder_add_file, to: "phototheque_espace_pro_folders#add_file", path: 'mediatheque/folders/:id/add_file'
      patch 'mediatheque/folders/:id/save_file', to: "phototheque_espace_pro_folders#save_file"
      get :mediateque_folder_delete_file, to: "phototheque_espace_pro_folders#delete_file", path: "mediatheque/folders/:id/delete"
      resources :slider_homes, only: [:index] do
        resources :slide_items, only: [:new,:create,:edit,:update,:destroy]
      end

    end

    resources :admin

    resources :crm do
      collection do
        get :prospects, to: 'crm#crm_prospects', path: ":id/prospects"
        get :show_prospect, :path => "show", path: "prospect/:id"
        get :new_prospect,to: 'crm#new_prospect', :path => "/new"
        get :edit_prospect, :path => "prospect/:id/edit"
        get :clients, to: "crm#crm_customers", path: ":id/clients"
        get :customer, to: "crm#show_customer", path: "/client/:id"
        get :new_customer, to: "crm#new_customer"
        get :edit_customer, to: "crm#edit_customer", path: "/client/:id/edit"

        get :instituts, to: "crm#instituts", path: "instituts"
        get :new_institut, to: "crm#new_institut"
        get :edit_institut, to: "crm#edit_institut", path: "instituts/:id/edit"
        post :create_institut, to: "crm#create_institut"

        get "delete_photo", to: "crm#delete_photo"
        get :statistiques, to: "crm#statistiques", path: ":id/statistiques"

        get :filter_up, to: "crm#filter_up"
        get :filter_down, to: "crm#filter_down"

        post :create_customer, to: "crm#create_customer"
        post :create_prospect, to: "crm#create_prospect"

        get :prospection, to: "crm#prospection"
        get :request_prospection, to: "crm#request_prospection"

        resources :orders

      end
      member do
        patch :update_prospect
        patch :update_customer, to: "crm#update_customer"
        patch :update_institut, to: "crm#update_institut"

        #get :prospects, to: 'crm#crm_prospects'
        #get :edit_prospect, :path => "edit"
        #patch :update_prospect
        #get :show_prospect, :path => "show"
        #get :clients, to: "crm#crm_customers"
        #get :new_customer, to: "crm#new_customer"
        #post :create_customer, to: "crm#create_customer"
        #get :new_institut, to: "crm#new_institut"
        ##get "/client", to: "crm#show_customer"
      end
    end




    resources :instituts, path:"instituts-beaute" do
      collection do
        get :send_contact, path:"send"
        get "/:region/:lieu", to: "instituts#lieu", as: :ville
        get "/villes",to: "instituts#villes", as: :all_villes
      end
    end

    get "/:category", to: "products#categories", as: :cosmetique_category
    post "/:category/filter", to: "products#filter", as: :filter_category

    #get "instituts-beaute/:region/:lieu", to: "instituts#lieu", as: :ville

  end
end

app/views/shared/_breadcrumb.html.erb
<div id="breadcrum">
  <p>Fil d'ariane</p>
</div>

app/views/shared/_carousel.html.erb
<div class="carousel" data-controller="carousel">
    <button data-action="carousel#previous" class="carousel-control left desktop"><%= image_tag("pictos/icon-nav-arrow-left.png", width:"15px", height:"30px") %></button>
    <button data-action="carousel#next" class="carousel-control right desktop"><%= image_tag("pictos/icon-nav-arrow-right.png", width:"15px", height:"30px")%></button>

    <button data-action="carousel#prevmobile" class="carousel-control left mobile"><%= image_tag("pictos/icon-nav-arrow-left.png",width:"15px", height:"30px")%></button>
    <button data-action="carousel#nextmobile" class="carousel-control right mobile"><%= image_tag("pictos/icon-nav-arrow-right.png", width:"15px", height:"30px")%></button>


  <div class="slides desktop">
    <% locals[:elements].each_slice(3).to_a.each_with_index do |element, index| %>
      <div data-carousel-target="slide" data-index="<%= index %>" class="slide grid three">

        <% element.each do |elmt|%>
          <div class="slide-card-content">
            <% if elmt[:photo].present? %>
              <%= image_tag elmt[:photo],class:"slide-card-img" %>
              <div class="slide-card-desc">
                <div class="slide-card-desc-info">
                  <div>
                    <h3><%= elmt[:name] %></h3>
                    <p><%= elmt[:description].truncate_words(25) %></p>
                  </div>
                  <div class="slide-card-desc-cta">
                    <% if !elmt[:model].nil? && elmt[:model] == "Soin" %>
                      <%= link_to "en savoir plus", soin_path(elmt[:lien]),class: "btn-rond"%>
                    <% elsif !elmt[:model].nil? && elmt[:model] == "Product" %>
                      <%= link_to "en savoir plus", product_path(elmt[:lien]),class: "btn-rond"%>
                    <%else %>
                      <%= link_to "en savoir plus", "",class: "btn-rond"%>
                    <% end %>
                  </div>
                </div>
              </div>
            <% else %>
            <%= image_tag ('https://res.cloudinary.com/dgznjnwgw/image/upload/v1706693201/static%20files/image-not-available_tmxyvm.jpg'),class:"slide-card-img" %>
              <div class="slide-card-desc">
                <div class="slide-card-desc-info">
                  <div>
                    <h3><%= elmt[:name] %></h3>
                    <p><%= elmt[:description].truncate_words(25) %></p>
                  </div>
                  <div class="slide-card-desc-cta">
                    <% if !elmt[:model].nil? && elmt[:model] == "Soin" %>
                      <%= link_to "en savoir plus", soin_path(elmt[:lien]),class: "btn-rond"%>
                    <% elsif !elmt[:model].nil? && elmt[:model] == "Product" %>
                      <%= link_to "en savoir plus", product_path(elmt[:lien]),class: "btn-rond"%>
                    <%else %>
                      <%= link_to "en savoir plus", "",class: "btn-rond"%>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>

          </div>
        <% end %>
      </div>
    <% end %>
  </div>


  <div class="slides mobile">
    <% locals[:elements].each_with_index do |element, index| %>
      <div data-carousel-target="slidemobile" data-index="<%= index %>" class="slide">
        <div class="slide-card-mobile-content">
          <% if element[:photo].present? %>
            <div class="slide-card-mobile-image">
              <%= image_tag element[:photo],class:"" %>
            </div>
            <div class="slide-card-mobile-desc">
              <h3><%= element[:name] %></h3>
              <p><%= element[:description].truncate_words(25) %></p>
              <% if !element[:model].nil? && element[:model] == "Soin" %>
                <%= link_to "en savoir plus", soin_path(element[:lien]),class: "btn-rond"%>
              <% elsif !element[:model].nil? && element[:model] == "Product" %>
                <%= link_to "en savoir plus", product_path(element[:lien]),class: "btn-rond"%>
              <% else %>
                <%= link_to "en savoir plus", "",class: "btn-rond"%>
              <% end %>
            </div>
          <% else %>
            <div class="slide-card-mobile-image">
              <%= image_tag ('https://res.cloudinary.com/dgznjnwgw/image/upload/v1706693201/static%20files/image-not-available_tmxyvm.jpg'),class:"" %>
            </div>
            <div class="slide-card-mobile-desc">
              <h3><%= element[:name] %></h3>
              <p><%= element[:description].truncate_words(25) %></p>
              <% if !element[:model].nil? && element[:model] == "Soin" %>
                <%= link_to "en savoir plus", soin_path(element[:lien]),class: "btn-rond"%>
              <% elsif !element[:model].nil? && element[:model] == "Product" %>
                <%= link_to "en savoir plus", product_path(element[:lien]),class: "btn-rond"%>
              <%else %>
                <%= link_to "en savoir plus", "",class: "btn-rond"%>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/shared/_carousel_show.html.erb
<div class="component_carousel" data-controller="institut">
  <% @photos = locals[:photos] %>
  <div class="carousel_cover" data-institut-target="imgcover">
    <% @photos.each do |photo|%>
      <%= image_tag photo, height:500,gravity:"face", class:"carousel_cover_img" %>
    <% end %>
  </div>

  <div class="carousel_img_control institut" data-institut-target="imgselect">
    <% if @photos.attached? %>
          <% @photos.each do |photo| %>
            <%= image_tag photo, width: 115,gravity:"face", class:"", data: {action: "click->institut#carrouselSelect"} %>
          <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_crm_nav.html.erb
<nav id="nav-crm">
  <div class="logo-nif"></div>
  <div class="menu">
    <ul>
        <li><%= link_to "Mes prospects", prospects_crm_index_path(current_commercial) %></li>
        <li><%= link_to "Mes clients", clients_crm_index_path(current_commercial)%></li>
        <li class="disable"><i class="fa-regular fa-envelope"></i>Mes messages</li>
        <li><%= link_to "Commandes",orders_path %></li>
        <li class="disable"><i class="fa-regular fa-calendar"></i>Mes rendez-vous</li>
        <li class="disable">FAQ</li>
        <li class="disable">Simulateur soins</li>
        <li><%= link_to "Prospection",prospection_crm_index_path %></li>
        <li><%= link_to "Statistiques", statistiques_crm_index_path(current_commercial) %></li>
        <li><%= link_to "Instituts", instituts_crm_index_path() %></li>
    </ul>
    <li class="btn_disconnect"><%= button_to(
          "Se déconnecter",
          destroy_user_session_path,
          method: :delete
        ) %>
      </li>
  </div>
</nav>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="footer">
  <!--
  <div class="footer_white"></div>
  -->
  <div class="footer-inside">

    <div class="footer gammes">
      <p>Nos gammes</p>
      <ul>
        <li><%= link_to "Visage",cosmetique_category_path(category:"visage")%></li>
        <li><%= link_to "corps",cosmetique_category_path(category:"corps")%></li>
        <li><%= link_to "Soins",soins_path %></li>
      </ul>
    </div>
    <div class="footer marque">
      <%= link_to "La marque"%>
    </div>
    <div class="footer contact">
      <%= link_to "Nous contacter", contact_path %>
      <%= link_to "Devenir partenaire",devenir_partenaire_path%>
      <%= link_to "Trouver un institut",instituts_path%>
    </div>
    <div class="footer blog">
      <%= link_to "Le blog"%>
      <%= link_to "Les formations", formations_path %>
      <%= link_to "Espace pro", espace_pro_index_path %>
    </div>
    <div class="footer social">
      <ul>
        <i class="fa-brands fa-facebook fa-2xl"></i>
        <i class="fa-brands fa-instagram fa-2xl"></i>
      </ul>
    </div>
    <div class="footer cgu">
      <%= link_to "Mentions légales", mentions_legales_path %>
      <%= link_to "Politique de confidentialite", politique_confidentialite_path %>
      <%= link_to "Gestion des cookies", gestion_cookies_path %>
      <%= link_to "Donnees personnelles", donnees_personnelles_path %>
    </div>

  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <%= render "shared/navbar2" %>
  <%= render "shared/mobile_nav2" %>
</header>

app/views/shared/_navbar.html.erb
<nav role="navigation" id="main-navbar">
  <ul>
    <li><%= link_to "Accueil", root_path %></li>
    <li><a href="#">Produits</a>
      <ul class="dropdown">
        <li><a href="#">Sub-1</a></li>
        <li><a href="#">Sub-2</a></li>
        <li><a href="#">Sub-3</a></li>
      </ul>
    </li>
    <li><%= link_to "Trouver un institut", "" %></li>
    <li><%= link_to "Ressources", "" %></li>
    <li><%= link_to "Espace pro", "" %></li>
    <li><%= link_to "Contact", "" %></li>
  </ul>
</nav>

app/views/shared/_navbar2.html.erb
<div id="desktop-nav" data-controller="fixed" class="fixed-nav">
<nav id="black-nav">
  <p>Découvrez le nouveau masque purifiant de notre gamme visage aux actifs de zinc et de concombre</p>
</nav>

  <nav id="white-nav" class="">
    <div>
      <%= link_to "Trouver son institut", instituts_path %>
    </div>
    <div>
      <%= link_to "Devenir partenaire",devenir_partenaire_path%>
      <%= link_to "Espace pro", espace_pro_index_path, class: "btn-espace-pro shadow" %>
    </div>
  </nav>
  <div data-controller="navbar">
  <nav id="main-nav" class="">
    <%= link_to root_path do %>
      <% if params[:action] == "home"  %>
        <h1><%= image_tag "logo-nif-pro.svg", class: "logo-home", alt: "Nature is Future Pro | Dédié aux professionnels de la beauté" %></h1>
      <%else%>
        <%= image_tag "logo-nif-pro.svg", class: "logo-home", alt:"logo nature is future pro" %>
      <% end %>
    <% end %>
    <ul class="nav-main-link">
      <div class="nav-left">
        <li class="nav-head" data-action="mouseover->navbar#mouseOver mouseout->navbar#mouseOut">
          <%= link_to "VISAGE", ""%>
          <!-- Nos gammes -->
          <div class="dropdown-nav" data-navbar-target="submenu">
            <div class="drop-test">
              <ul class="dropdown-list">
                <p class="menu-title">NOS PRODUITS VISAGE</p>
                <div style="columns: 2;">
                  <% @pdts_nav_visage.each do |pdt| %>
                    <li><%= link_to pdt.name, product_path(pdt) %></li>
                  <% end %>
                  <li><%= link_to "Tous nos produits",cosmetique_category_path(category:"visage") %></li>
                </div>
              </ul>
              <!-- Types de produits -->
              <ul class="dropdown-list">
                <p class="menu-title">TYPES DE PRODUIT</p>
                <% @type_produits_visage.each do |type| %>
                  <li><%= link_to type.capitalize, type_product_products_path(category:"visage",type_product: type.downcase) %></li>
                <% end %>
              </ul>
              <!-- Besoins -->
              <ul class="dropdown-list">
                <p class="menu-title">PRÉOCCUPATIONS</p>
                <% @preoccupations_visage.each do |preoc| %>
                  <li><%= link_to preoc.capitalize, besoin_products_path(category: "visage",besoin: preoc.downcase) %></li>
                <% end %>

              </ul>
              <!-- Nos nouveautés -->
              <ul class="dropdown-list last">
                <p class="menu-title">NOS NOUVEAUTÉS</p>
                <a href="">
                  <img src="https://www.natureisfuture.fr/1235-home_default/gommage-doux-100ml.jpg" widht="300">
                </a href="">
              </ul>
            </div>
            <!-- Fin du sub menu-->
          </div> <!-- Fin du .dropdown-nav -->
        </li>
        <li class="nav-head" data-action="mouseover->navbar#mouseOver mouseout->navbar#mouseOut">
          <%= link_to "CORPS", ""%>
          <!-- Nos gammes -->
          <div class="dropdown-nav" data-navbar-target="submenu">
            <div class="drop-test">
              <ul class="dropdown-list">
                <p class="menu-title">NOS PRODUITS CORPS</p>
                <% @pdts_nav_corps.each do |pdt| %>
                  <li><%= link_to pdt.name, product_path(pdt) %></li>
                <% end %>
                <li><%= link_to "Tous nos produits",cosmetique_category_path(category:"corps") %></li>
              </ul>
              <!-- Types de produits -->
              <ul class="dropdown-list">
                <p class="menu-title">TYPE DE PRODUIT</p>
                <% @type_produits_corps.each do |type| %>
                  <li><%= link_to type.capitalize, type_product_products_path(category:"corps",type_product: type.downcase) %></li>
                <% end %>
              </ul>
              <!-- Besoins -->
              <ul class="dropdown-list">
                <p class="menu-title">PRÉOCCUPATIONS</p>
                <% @preoccupations_corps.each do |preoc| %>
                  <li><%= link_to preoc.capitalize, besoin_products_path(category: "corps",besoin: preoc.downcase) %></li>
                <% end %>
              </ul>
            </div>
            <!-- Fin du sub menu-->
          </div> <!-- Fin du .dropdown-nav -->
        </li>
        <li class="nav-head" data-action="mouseover->navbar#mouseOver mouseout->navbar#mouseOut">
          <%= link_to "SOIN", ""%>
          <div class="dropdown-nav" data-navbar-target="submenu">
            <div class="drop-test">
              <ul class="dropdown-list">
                <p class="menu-title">SOIN VISAGE</p>
                  <% @soins_visage.each do |pdt| %>
                    <li><%= link_to pdt.name, soin_path(pdt) %></li>
                  <% end %>
              </ul>

              <ul class="dropdown-list">
                <p class="menu-title">SOIN CORPS</p>
                  <% @soins_corps.each do |pdt| %>
                    <li><%= link_to pdt.name, soin_path(pdt) %></li>
                  <% end %>
              </ul>

              <ul class="dropdown-list">
                <p class="menu-title">MASSAGES</p>
                <% @soins_massages.each do |pdt| %>
                    <li><%= link_to pdt.name, soin_path(pdt) %></li>
                  <% end %>
                <p></p>
                <li><%= link_to "Tous nos soins",soins_path %></li>
              </ul>
            </div>
          </div>
        </li>

        <li class="nav-head" data-action="mouseover->navbar#mouseOver mouseout->navbar#mouseOut">
          <%= link_to "LA MARQUE", ""%>
          <div class="dropdown-nav" data-navbar-target="submenu">
            <div class="drop-test">
              <ul class="dropdown-list">
                <li><%= link_to "Notre histoire", "" %></li>
                <li><%= link_to "Charte qualité", "" %></li>
                <li><%= link_to "Notre mission", "" %></li>
              </ul>
            </div>
          </div>
        </li>

      </div>
      <!-- Fin partie gauche -->
      <div class="nav-right">
        <li class="nav-head" data-action="mouseover->navbar#mouseOver mouseout->navbar#mouseOut">
          <%= link_to "FORMATION", formations_path %>
        </li>
        <li class="nav-head" data-action="mouseover->navbar#mouseOver mouseout->navbar#mouseOut">
          <%= link_to "JOURNAL", ""%>
        </li>
        <li class="nav-head" data-action="mouseover->navbar#mouseOver mouseout->navbar#mouseOut">
          <%= link_to "CONTACT", contact_path %>
        </li>
        <li class="nav-head" data-action="mouseover->navbar#mouseOver mouseout->navbar#mouseOut">
          <%= link_to "E-SHOP", "https://www.natureisfuture.fr/fr/"%>
        </li>
      </div>
      <!-- Fin partie droite -->
    </ul>
  </nav>
  <div class="menu-green" data-navbar-target="menugreen">
  </div>
  </div>
</div><!--Fin de fixed-nav -->

app/views/shared/_navbar_footer.html.erb
<div class="sous-menu-footer">
  <%= link_to "E-SHOP","", class: "btn-custom" %>
  <%= link_to "NOUS CONTACTER",contact_path, class: "btn-custom" %>
</div>

app/views/shared/_slider_home.html.erb
<div class="slider_home_container" data-controller="home">
<div class="slider">
        <div class="list">
          <% if !locals[:slider].nil? %>
            <% locals[:slider].slide_items.each do |slide| %>
              <div class="item">
                  <a href=<%= slide.link %>>
                    <% if slide.photo.attached? %>
                      <%= image_tag slide.photo %>
                    <% end %>
                  </a>
              </div>
            <% end %>
          <% end %>
        </div>
        <div class="buttons">
            <button id="prev"><%= image_tag "pictos/slider_row_left.svg", width:30 %></button>
            <button id="next"><%= image_tag "pictos/slider_row_right.svg", width:30 %></button>
        </div>
        <ul class="dots">
          <% if !locals[:slider].nil? %>
            <li class="active"></li>
            <% (locals[:slider].slide_items.size-1).times do |elt|%>
              <li class=""></li>
            <% end %>
          <% end %>
        </ul>
    </div>
</div>

<script type="text/javascript">
</script>