config/routes.rb
Rails.application.routes.draw do

  devise_for :customers
  devise_for :commercials
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  #get '/contact', to: redirect('/instituts', status: 301) #Test redirection
  get "/fr/instituts-bio", to: redirect('/fr/instituts-beaute', status: 301)
  get "/fr/instituts-de-beaute-bio", to: redirect('/fr/instituts-beaute', status: 301)
  get "/fr/instituts-beaute-bio", to: redirect('/fr/instituts-beaute', status: 301)

  get "/fr/instituts-beaute-bio/nature-creative", to: redirect('/fr/instituts-beaute/nature-creative', status: 301)
  get "/fr/instituts-beaute-bio/rita-esthetique", to: redirect('/fr/instituts-beaute/rita-esthetique', status: 301)
  get "/fr/instituts-beaute-bio/liesse-beaute", to: redirect('/fr/instituts-beaute/liesse-beaute', status: 301)
  get "/fr/instituts-beaute-bio/le-clos-des-sources", to: redirect('/fr/instituts-beaute/le-clos-des-sources', status: 301)
  get "/fr/instituts-beaute-bio/ali-s-heaven-institut", to: redirect('/fr/instituts-beaute/ali-s-heaven-institut', status: 301)
  get "/fr/instituts-beaute-bio/zen-ment-belle", to: redirect('/fr/instituts-beaute/zen-ment-belle', status: 301)
  get "/fr/instituts-beaute-bio/liesse-beaute", to: redirect('/fr/instituts-beaute/liesse-beaute', status: 301)


  #get '/fr/contact', to: redirect('/fr/instituts-beaute', status: 302)
  # Defines the root path route ("/")
  scope "(:locale)", locale: /fr/ do
    root to: "pages#home"
    get "contact", to: "pages#contact"
    get "envoye", to: "pages#send_contact"
    get "formations", to: "pages#formations"
    get "donnees-personnelles",to: "pages#donnees"
    get "politique-confidentialite",to: "pages#confidentialite"
    get "gestion-cookies",to: "pages#cookies"
    get "mentions-legales",to:"pages#mentions"
    get "devenir-partenaire",to:"pages#devenir_partenaire"
    get "/instituts-beaute/region/:region", to: "pages#region", as: :region
    get :send_partenaire, to:"pages#send_partenaire",path:"send_partenaire"



    resources :espace_pro, path: "/espace-pro" do
      member do
        get "etablissements", to: "espace_pro#etablissements"
        get "cours-formations", to: "espace_pro#cours"
        get "commandes",to: "espace_pro#commandes"
        get "rendez-vous", to:"espace_pro#rdv"
        get "statistiques",to:"espace_pro#statistiques"
        get "edit_profile", to: "espace_pro#edit_profile"
        patch "update_profile", to: "espace_pro#update_profile"
        resources :custom_soins, only: [:index,:new,:create,:edit,:update,:destroy], path:"soins-personnalises"
        resources :cartes, only: [:new,:create,:show,:destroy]
        resources :stock_instituts, only: [:index,:edit,:update], path: "stock"
        resources :courses, only: [:index, :show]
        resources :carte_cadeaus, only: [:index,:show,:new,:create,:destroy], path: "cheques-cadeau"
        get :send_cheque, to: "carte_cadeaus#send_cheque"
        get :update_status, to: "espace_pro#update_status"
        #get :note_to_message, to: "espace_pro#note_to_message"
        post :addnote, to: "espace_pro#addnote"
        get "mediatheque",to: "espace_pro#phototheque"
        get :mediatheque_folder,to: "espace_pro#phototheque_folder", path:"/mediatheque/folders/:folder_id"
      end
      collection do
        get "produits", to: "espace_pro#produits"
        get "faq",to:"espace_pro#faq"
        get :institut, to: "espace_pro#institut_show", path: "/etablissements/:id"
        get :edit_institut, to: "espace_pro#edit_institut", path: "/etablissements/:id/edit"
        patch :update_institut, to: "espace_pro#update_institut"
        get "delete_photo", to: "espace_pro#delete_photo"
        get "delete_promo", to: "espace_pro#delete_promo"
        get "soins",to:"espace_pro#soins"
      end
    end

    resources :profiles

    resources :blog_posts, only: [:index,:show], path:"blog"

    resources :products, path: "cosmetiques" do
      member do
        get "delete_photo"
      end
      collection do
        #get "/filtres", to: "products#filtres",as: :cosmetique_filtres
        get "click-and-collect",to: "products#click_and_collect", as: :click_collect
        get :besoin, to: "products#type_besoin", path: "/preoccupation/:besoin"
        get :type_product, to: "products#type_product", path: "/type-produit/:type_product"
      end
    end
    #get "/corps", to: "products#category", as: :cosmetique_corps
    resources :soins do
      collection do
        get :visage
        get :corps
        get :massages
        get "cat_bis", to: "soins#cat_bis"
        get :reserver, to: "soins#reservation", path: "/reserver/:soin"
      end
    end
    post "soins/filter", to: "soins#filter"


    scope '/admin' do
      resources :team_members
      resources :prospects
      resources :courses, only: [:new,:create,:edit,:update,:destroy]
      resources :blog_posts, only: [:new,:create,:edit,:update,:destroy]
      get :all_posts, to: "admin#all_posts"
      resources :chapters, only: [:new,:create,:edit,:update,:destroy]
      get "/soins", to: "admin#admin_soins", as: :admin_soins
      get :clients, to: "admin#customers", path: "/clients"
      get :client, to: "admin#customer", path: "/clients/:id"
      get "/tous-les-cours", to: "admin#cours"
      get :instituts, to: "admin#instituts", as: :admin_instituts
      get :preview, to: "courses#preview", path: "/courses/:id/preview"
      get :edit_home_content, to: "admin#edit_home_content"
      post :update_home_content, to: "admin#update_home_content"

      get 'mediatheque', to: "phototheque_espace_pros#index"
      get 'mediatheque/add_file', to: "phototheque_espace_pros#add_file"
      patch 'mediatheque/save_file', to: "phototheque_espace_pros#save_file"
      get :delete_file, to: "phototheque_espace_pros#delete_file", path: "mediatheque/:id/delete"

      resources :phototheque_espace_pro_folders, only: [:new,:create,:show,:edit,:update,:destroy],path: "mediatheque/folders"
      get :mediateque_folder_add_file, to: "phototheque_espace_pro_folders#add_file", path: 'mediatheque/folders/:id/add_file'
      patch 'mediatheque/folders/:id/save_file', to: "phototheque_espace_pro_folders#save_file"
      get :mediateque_folder_delete_file, to: "phototheque_espace_pro_folders#delete_file", path: "mediatheque/folders/:id/delete"
      resources :slider_homes, only: [:index] do
        resources :slide_items, only: [:new,:create,:edit,:update,:destroy]
      end

    end

    resources :admin

    resources :crm do
      collection do
        get :prospects, to: 'crm#crm_prospects', path: ":id/prospects"
        get :show_prospect, :path => "show", path: "prospect/:id"
        get :new_prospect,to: 'crm#new_prospect', :path => "/new"
        get :edit_prospect, :path => "prospect/:id/edit"
        get :clients, to: "crm#crm_customers", path: ":id/clients"
        get :customer, to: "crm#show_customer", path: "/client/:id"
        get :new_customer, to: "crm#new_customer"
        get :edit_customer, to: "crm#edit_customer", path: "/client/:id/edit"

        get :instituts, to: "crm#instituts", path: "instituts"
        get :new_institut, to: "crm#new_institut"
        get :edit_institut, to: "crm#edit_institut", path: "instituts/:id/edit"
        post :create_institut, to: "crm#create_institut"

        get "delete_photo", to: "crm#delete_photo"
        get :statistiques, to: "crm#statistiques", path: ":id/statistiques"

        get :filter_up, to: "crm#filter_up"
        get :filter_down, to: "crm#filter_down"

        post :create_customer, to: "crm#create_customer"
        post :create_prospect, to: "crm#create_prospect"

        get :prospection, to: "crm#prospection"
        get :request_prospection, to: "crm#request_prospection"

        resources :orders

      end
      member do
        patch :update_prospect
        patch :update_customer, to: "crm#update_customer"
        patch :update_institut, to: "crm#update_institut"

        #get :prospects, to: 'crm#crm_prospects'
        #get :edit_prospect, :path => "edit"
        #patch :update_prospect
        #get :show_prospect, :path => "show"
        #get :clients, to: "crm#crm_customers"
        #get :new_customer, to: "crm#new_customer"
        #post :create_customer, to: "crm#create_customer"
        #get :new_institut, to: "crm#new_institut"
        ##get "/client", to: "crm#show_customer"
      end
    end




    resources :instituts, path:"instituts-beaute" do
      collection do
        get :send_contact, path:"send"
        get "/:region/:lieu", to: "instituts#lieu", as: :ville
        get "/villes",to: "instituts#villes", as: :all_villes
      end
    end

    get "/:category", to: "products#categories", as: :cosmetique_category
    post "/:category/filter", to: "products#filter", as: :filter_category

    #get "instituts-beaute/:region/:lieu", to: "instituts#lieu", as: :ville

  end
end

app/models/institut.rb
class Institut < ApplicationRecord

  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :customer
  geocoded_by :full_address
  after_validation :geocode, if: :will_save_change_to_address?
  after_initialize :init_horaires
  has_many_attached :photos
  has_one_attached :promo_photo
  has_one :carte, dependent: :destroy
  has_rich_text :content
  has_many :message_instituts, dependent: :destroy
  has_one :stock_institut, dependent: :destroy

  after_create :init_stock

  CATEGORIES = ["institut de beauté","day spa"]
  TELS = {
    "FR": "+33",
    "BE": "+32",
    "LU": "+352",
    "CH": "+41",
    "AD": "+376",
    "MC": "+377"
  }

  def full_address
    [address, cp, city, country].compact.join(', ')
  end

  def init_horaires
    self.horaires ||= { lundi: {am_1:"",am_2:"",pm_1:"",pm_2:""},mardi: {am_1:"",am_2:"",pm_1:"",pm_2:""},mercredi: {am_1:"",am_2:"",pm_1:"",pm_2:""},jeudi: {am_1:"",am_2:"",pm_1:"",pm_2:""},vendredi: {am_1:"",am_2:"",pm_1:"",pm_2:""},samedi: {am_1:"",am_2:"",pm_1:"",pm_2:""},dimanche: {am_1:"",am_2:"",pm_1:"",pm_2:""}}.to_json
  end

  def init_stock
    StockInstitut.create(institut_id:self.id)
  end

end

app/controllers/instituts_controller.rb
class InstitutsController < ApplicationController
  add_breadcrumb "Home".upcase, :root_path
  def index
    add_breadcrumb "<strong>Instituts de beauté</strong>".upcase.html_safe, instituts_path

    @page_title = "Instituts de beauté bio | Nature is Future Pro"
    @page_description = "Trouvez un institut de beauté appliquant des soins certifiés bio proche de chez vous"

    if params[:soin].present? && !params[:soin].blank?
      id_soin = Soin.friendly.find(params[:soin]).id
      cartes_valid = []
      instituts = []
      Carte.all.each do |carte|
        cartes_valid << carte if carte.soins.pluck(:id).include?(id_soin)
      end

      cartes_valid.pluck(:institut_id).each do |inst_id|
        instituts << Institut.find(inst_id)
      end
      @instituts = Institut.where(id: instituts.map(&:id))
    else
      @instituts = Institut.all
    end
    # The `geocoded` scope filters only flats with coordinates
    @markers = @instituts.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {flat: flat}),
        marker_html: render_to_string(partial: "marker", locals: {flat: flat})
      }
    end
    @regions = YAML.load_file("#{Rails.root.to_s}/db/yaml/villes_instituts.yml")
  end

  def show
    #@institut = Institut.find(params[:id])

    @institut = Institut.friendly.find(params[:id])

    add_breadcrumb "Instituts de beauté".upcase.html_safe, instituts_path
    add_breadcrumb "<strong>#{@institut.name.upcase}</strong>".html_safe, institut_path

    @page_title = "#{@institut.name} | Institut de beauté bio à #{@institut.city}"
    @page_description = ""

    @flat = @institut
    @soins = []
    if @institut.carte.present?
      @institut.carte.carte_soins.each do |soin|
        @soins << soin.soin if soin.soin_id != nil
        @soins << soin.custom_soin if soin.custom_soin != nil
      end
    end
    #require 'uri'

    #adresse = @institut.full_address
    #@adresse_encodee = "https://www.google.com/maps/place/#{URI.encode_www_form_component(adresse)}"

    @soins.sort_by(&:category)

    key_api = ENV["GOOGLE_MAP_API"]
    if @institut.place_id.present?
      place_id = @institut.place_id
      response = HTTParty.get("https://maps.googleapis.com/maps/api/place/details/json?placeid=#{place_id}&reviews_no_translations=true&translated=false&reviews_sort=newest&key=#{key_api}")

      data = response.parsed_response
      @total_reviews = data["result"]["user_ratings_total"]
      @rating = data["result"]["rating"]
      @reviews = data["result"]["reviews"]
    end

    #@soins << @institut.soins
    #@soins << @institut.custom_soins

    if @institut.category == "institut de beauté"
      @inst_structured_data_cat = "BeautySalon"
    elsif @institut.category == "day spa"
      @inst_structured_data_cat = "DaySpa"
    end
    @marker = [{
        lat: @flat.latitude,
        lng: @flat.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {flat: @flat}),
        marker_html: render_to_string(partial: "marker", locals: {flat: @flat})
      }]
  #[{:lat=>49.6312952, :lng=>1.8207573, :info_window_html=>"<h2>Test etablissement</h2>\n<p>13 rue principale</p>\n", :marker_html=>"<img height=\"30\" width=\"30\" alt=\"Logo\" src=\"/assets/logo-ecf839a7ae9d8c3650270ea01ceb8d45ef0f33459d9b14df8e780355ddf57533.png\" />\n"}]
  ahoy.track "institut_view", page_name: @institut.name, institut_id:@institut.id
  end

  def new
    @institut = Institut.new
    @customer = Customer.find(params[:customer])
  end

  def create
    @institut = Institut.new(institut_params)

    if @institut.email.blank?
      @institut.email = @institut.customer.email
    end
    @institut.save
    if @institut.save
      redirect_to admin_index_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def lieu
    @ville = params[:lieu]
    @region = params[:region].capitalize

    add_breadcrumb "Instituts de beauté".upcase.html_safe, instituts_path
    add_breadcrumb "<strong>#{@ville.upcase}</strong>".html_safe

    @page_title = "Instituts de beauté bio à #{@ville} | Nature is Future Pro"
    @page_description = "Trouvez un institut de beauté ou une esthéticienne à #{@ville} ou aux alentours utilisant des produits certifiés bio"

    villes_yml = YAML.load_file("#{Rails.root.to_s}/db/yaml/villes_instituts.yml")[params[:region].capitalize]

    xx = ""
    villes_yml.keys.each do |key|
      if villes_yml[key]["villes"][params[:lieu].capitalize] != nil
        xx = villes_yml[key]["villes"][params[:lieu].capitalize].values
      else villes_yml[key]["villes"][params[:lieu].capitalize].nil?
      end
    end
    latlng = xx
    if latlng == [] || latlng == nil
      results = Geocoder.search(params[:lieu])
      latlng = results.first.coordinates
    end

    @instituts = Institut.near(latlng,10)
    @markers = @instituts.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {flat: flat}),
        marker_html: render_to_string(partial: "marker", locals: {flat: flat})
      }
    end

    if YAML.load_file("#{Rails.root.to_s}/db/yaml/cover_villes.yml")[params[:lieu]] != nil
      @cover = YAML.load_file("#{Rails.root.to_s}/db/yaml/cover_villes.yml")[params[:lieu]]["cover"]
    else
      @cover = YAML.load_file("#{Rails.root.to_s}/db/yaml/cover_villes.yml")["default_town"]["cover"]
    end
    @other_towns = @instituts.map(&:city)
    @other_towns = @other_towns.reject {|town| town == params[:lieu].capitalize }
    @other_towns = @other_towns.uniq

  end

  def villes
  end

  def send_contact
    if params[:hidden_message].present?
      redirect_to request.referrer
    else
      # Logic to handle the form submission
      @institut = Institut.find(params[:contact][:institut_id])
      @institut_name = @institut.name
      @gerant_firstname = @institut.customer.firstname

      @gerant_email = @institut.customer.email
      @gerant_tel = @institut.customer.tel

      @lastname = params[:contact][:lastname]
      @firstname = params[:contact][:firstname]
      @email_client = params[:contact][:email]
      @tel_client = params[:contact][:tel]
      @date = params[:contact][:date]
      @message = params[:contact][:message]
      if params[:contact][:rgpd] == "1"
        @rgpd = true
      else
        @rgpd = false
      end
      @soin_select = params[:contact][:hidden_soin]
      InstitutMailer.with(gerant_email:@gerant_email,lastname:@lastname,firstname:@firstname,email_client:@email_client,tel_client:@tel_client,date:@date,message:@message,soin:@soin_select,rgpd:@rgpd, institut_name:@institut_name,gerant_firstname:@gerant_firstname,gerant_tel:@gerant_tel).nouvelle_demande.deliver_later
      puts "Email envoyé"
      ahoy.track "institut_rdv_send", page_name: @institut.name, institut_id:@institut.id

      message = MessageInstitut.new(
        institut_id:@institut.id, message:params[:contact][:message],expediteur:"#{@lastname} #{@firstname}",
        tel:@tel_client,date:@date,email:@email_client
      )
      message.save
      redirect_to institut_path(@institut),notice: "Votre message a été envoyée avec succès"

      #Email.create(email: params[:email])
      #redirect_to request.referrer
    end

  end

  private
  def institut_params
    params.require(:institut).permit(:name,:address,:city,:cp,:latitude,:longitude,:place_id,:email,:website,:customer_id,:promo_photo,photos: [])
  end
end

app/helpers/instituts_helper.rb
module InstitutsHelper
end

app/views/instituts/_contact.html.erb
<div class="custom_form institut_show" data-controller="contact">
  <%= simple_form_for :contact, {url: send_contact_instituts_path, method: "get" } do |f| %>
    <div class="flex">
      <%= f.input :lastname, label:"",placeholder:"Nom", input_html: { required: true } %>
      <%= f.input :firstname, label:"",placeholder:"Prénom", input_html: { required: true } %>
    </div>
    <div class="flex">
      <%= f.input :email, label:"",placeholder:"Email", input_html: { required: true } %>
      <%= f.input :tel, label:"",placeholder:"Tel", input_html: { required: true } %>
    </div>
    <%= f.email_field :hidden_message, placeholder: 'Message', class: 'hidden-message' %>
    <div class="">
      <!--
      <%= f.input :soin, collection: @soins, selected: 1,input_html: {data: {contact_target: "soin", action:"focusout->contact#selectValue"}} %>
      -->
      <%= f.input :date, label:"",placeholder:"Date souhaitée",as: :date, html5: true, required: false %>
    </div>
    <div>
      <%= f.input :message, label:"",placeholder:"Message", as: :text,:input_html => {:rows => 5},required:false %>
      <%= f.hidden_field :institut_id, value: @institut.id %>
    </div>
    <div class="rgpd">
    <%= f.input :rgpd, as: :boolean,required: true , label:"J'accepte que mes coordonées soient collectées dans le cadre de ma demande" %>
    </div>
    <%= f.input :hidden_soin,as: :hidden, class: 'hidden-message', input_html: {data: {contact_target: "hiddenSoin"} } %>
    <div class="form_btn">
      <%= f.submit "Envoyer", class: "btn-rond" %>
    </div>
  <% end %>
</div>

app/views/instituts/_horaires.html.erb
<table>
  <tbody>
    <tr>
      <td>Lundi</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>Mardi</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>Mercredi</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>Jeudi</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>Vendredi</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>Samedi</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>Dimanche</td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

app/views/instituts/_marker.html.erb
<%= image_tag "marker-nif.png", height:"", width: 25, alt: "Logo" %>

app/views/instituts/create.html.erb
<h1>Instituts#create</h1>
<p>Find me in app/views/instituts/create.html.erb</p>

app/views/instituts/destroy.html.erb
<h1>Instituts#destroy</h1>
<p>Find me in app/views/instituts/destroy.html.erb</p>

app/views/instituts/edit.html.erb
<h1>Instituts#edit</h1>
<p>Find me in app/views/instituts/edit.html.erb</p>

app/views/instituts/index.html.erb
<article id="instituts_list" itemscope itemtype="https://schema.org/<%= @inst_structured_data_cat %>">
<section>
<div class="instituts_intro">
  <%= image_tag "institut-cabine.png", height:250 %>
  <div>
    <h1>Nos instituts de beauté bio partenaires</h1>
    <p>Nos différents <strong>instituts de beauté</strong> partenaires ont choisi d’utiliser des produits <strong>cosmétiques bio et naturels</strong> dans leurs différents soins de beauté pour vous offrir le meilleur pour votre peau.
Les instituts de beauté, spa et esthéticiennes à domicile vous attendent pour utiliser le meilleur des plantes pour vous sublimer.
</p>
  </div>
</div>
</section>

<div style="width: 100%; height: 520px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>
<!--
  <section class="instituts_villes">
  <ul>
  <li>Strasbourg</li>
  <li>Paris</li>
  <li>Marseille</li>
  <li></li>
  <li></li>
  </ul>
  <%= link_to "voir les autres villes", all_villes_instituts_path %>
  </section>
  -->
  <section data-controller="institut" class="instituts_list_regions">
    <% @instituts.group_by(&:region).each do |region| %>
      <h2><%= region[0] %></h2>
      <ul class="grid_instituts four">
          <% region[1].each do |institut| %>
            <li class="instituts_card">
              <div class="institut_card__name">
                <h3 class="institut_card_titre"><%= institut.name %></h3>
                <p class="institut_card_ville"><%= institut.city %> (<%= institut.cp[0..1] %>)</p>
              </div>
              <div class="instituts_accordion">
                <div class="">
                  <span class="toggle_accordion_map" data-action="click->institut#accordionToggle"><i class="fa-sharp fa-solid fa-plus"></i></span>
                </div>
                <div class="instituts_accordion_hide" data-institut-target="contentHide">
                  <table>
                        <tbody>
                          <% institut.horaires.each do |key,value|%>
                            <tr>
                              <td><%= key.upcase %></td>
                              <% if value.values.first(2).first == value.values.first(2).last %>
                                <td><%= value["am_1"].capitalize %></td>
                              <% else %>
                                <td><%= value["am_1"].capitalize %> - <%= value["am_2"].capitalize %></td>
                              <% end %>
                              <% if value.values.last(2).first == value.values.last(2).last %>
                                <td><%= value["pm_1"].capitalize %></td>
                              <% else %>
                                <td><%= value["pm_1"].capitalize %> - <%= value["pm_2"].capitalize %></td>
                              <% end %>
                            <tr>
                          <% end %>
                        </tbody>
                      </table>
                  <%= link_to "En savoir plus", institut_path(institut), class:"btn-rond black" %>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
    <% end %>
  </section>
  <section class="links_lieux">
    <% @regions.keys.each do |region|%>
      <%= link_to region.capitalize, region_path(region.downcase)%>
    <% end %>
  </section>
</article>

app/views/instituts/lieu.html.erb
<article id="instituts_list">
  <section>
    <div class="instituts_intro">
      <%= image_tag @cover,height:250 %>
      <div>
        <h1>Instituts de beauté bio à <%= @ville.capitalize %></h1>
        <p>Les <strong>instituts de beauté situés à <%= @ville.capitalize %></strong> et aux alentours.
  Retrouvez l’ensemble des instituts et des esthéticiennes partenaires utilisant nos produits certifiés bio dans leurs soins.</p>
      </div>
    </div>
  </section>
  <section data-controller="institut" class="instituts_list_regions">
    <% @instituts.group_by(&:region).each do |region| %>
      <ul class="grid_instituts four">
          <% region[1].each do |institut| %>
            <li class="instituts_card">
              <div class="institut_card__name">
                <h3 class="institut_card_titre"><%= institut.name %></h3>
                <p class="institut_card_ville"><%= institut.city %> (<%= institut.cp[0..1] %>)</p>
              </div>
              <div class="instituts_accordion">
                <div class="">
                  <span class="toggle_accordion_map" data-action="click->institut#accordionToggle"><i class="fa-sharp fa-solid fa-plus"></i></span>
                </div>
                <div class="instituts_accordion_hide" data-institut-target="contentHide">
                  <table>
                        <tbody>
                          <% institut.horaires.each do |key,value|%>
                            <tr>
                              <td><%= key.upcase %></td>
                              <% if value.values.first(2).first == value.values.first(2).last %>
                                <td><%= value["am_1"].capitalize %></td>
                              <% else %>
                                <td><%= value["am_1"].capitalize %> - <%= value["am_2"].capitalize %></td>
                              <% end %>
                              <% if value.values.last(2).first == value.values.last(2).last %>
                                <td><%= value["pm_1"].capitalize %></td>
                              <% else %>
                                <td><%= value["pm_1"].capitalize %> - <%= value["pm_2"].capitalize %></td>
                              <% end %>
                            <tr>
                          <% end %>
                        </tbody>
                      </table>
                  <%= link_to "En savoir plus", institut_path(institut), class:"btn-rond black" %>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
    <% end %>
    <% if @other_towns.size != 0%>
    <div>
      <h2>Voir les autres villes autour de <%= @ville.capitalize %></h2>
      <ul class="links_lieux">
      <% @other_towns.each do |town| %>
        <li><%= link_to town.capitalize, ville_instituts_path(@region,town.downcase) %></li>
      <% end %>
      </ul>
    </div>
    <% end %>
  </section>
</article>

app/views/instituts/new.html.erb
<h1>Instituts#new</h1>
<p>Find me in app/views/instituts/new.html.erb</p>

<%= simple_form_for @institut do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :cp %>
  <%= f.input :city %>
  <%= f.input :country, selected: "FR" %>
  <%= f.input :description, as: :text, input_html: {rows: 10 } %>
  <%= f.hidden_field :customer_id, value: params[:customer]  %>
  <%= f.button :submit %>
<% end %>

app/views/instituts/update.html.erb
<h1>Instituts#update</h1>
<p>Find me in app/views/instituts/update.html.erb</p>

app/views/instituts/villes.html.erb
<h1>All villes</h1>