config/routes.rb
Rails.application.routes.draw do

  devise_for :customers
  devise_for :commercials
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  #get '/contact', to: redirect('/instituts', status: 301) #Test redirection
  get "/fr/instituts-bio", to: redirect('/fr/instituts-beaute', status: 301)
  get "/fr/instituts-de-beaute-bio", to: redirect('/fr/instituts-beaute', status: 301)
  get "/fr/instituts-beaute-bio", to: redirect('/fr/instituts-beaute', status: 301)

  get "/fr/instituts-beaute-bio/nature-creative", to: redirect('/fr/instituts-beaute/nature-creative', status: 301)
  get "/fr/instituts-beaute-bio/rita-esthetique", to: redirect('/fr/instituts-beaute/rita-esthetique', status: 301)
  get "/fr/instituts-beaute-bio/liesse-beaute", to: redirect('/fr/instituts-beaute/liesse-beaute', status: 301)
  get "/fr/instituts-beaute-bio/le-clos-des-sources", to: redirect('/fr/instituts-beaute/le-clos-des-sources', status: 301)
  get "/fr/instituts-beaute-bio/ali-s-heaven-institut", to: redirect('/fr/instituts-beaute/ali-s-heaven-institut', status: 301)
  get "/fr/instituts-beaute-bio/zen-ment-belle", to: redirect('/fr/instituts-beaute/zen-ment-belle', status: 301)
  get "/fr/instituts-beaute-bio/liesse-beaute", to: redirect('/fr/instituts-beaute/liesse-beaute', status: 301)


  #get '/fr/contact', to: redirect('/fr/instituts-beaute', status: 302)
  # Defines the root path route ("/")
  scope "(:locale)", locale: /fr/ do
    root to: "pages#home"
    get "contact", to: "pages#contact"
    get "envoye", to: "pages#send_contact"
    get "formations", to: "pages#formations"
    get "donnees-personnelles",to: "pages#donnees"
    get "politique-confidentialite",to: "pages#confidentialite"
    get "gestion-cookies",to: "pages#cookies"
    get "mentions-legales",to:"pages#mentions"
    get "devenir-partenaire",to:"pages#devenir_partenaire"
    get "/instituts-beaute/region/:region", to: "pages#region", as: :region
    get :send_partenaire, to:"pages#send_partenaire",path:"send_partenaire"



    resources :espace_pro, path: "/espace-pro" do
      member do
        get "etablissements", to: "espace_pro#etablissements"
        get "cours-formations", to: "espace_pro#cours"
        get "commandes",to: "espace_pro#commandes"
        get "rendez-vous", to:"espace_pro#rdv"
        get "statistiques",to:"espace_pro#statistiques"
        get "edit_profile", to: "espace_pro#edit_profile"
        patch "update_profile", to: "espace_pro#update_profile"
        resources :custom_soins, only: [:index,:new,:create,:edit,:update,:destroy], path:"soins-personnalises"
        resources :cartes, only: [:new,:create,:show,:destroy]
        resources :stock_instituts, only: [:index,:edit,:update], path: "stock"
        resources :courses, only: [:index, :show]
        resources :carte_cadeaus, only: [:index,:show,:new,:create,:destroy], path: "cheques-cadeau"
        get :send_cheque, to: "carte_cadeaus#send_cheque"
        get :update_status, to: "espace_pro#update_status"
        #get :note_to_message, to: "espace_pro#note_to_message"
        post :addnote, to: "espace_pro#addnote"
        get "mediatheque",to: "espace_pro#phototheque"
        get :mediatheque_folder,to: "espace_pro#phototheque_folder", path:"/mediatheque/folders/:folder_id"
      end
      collection do
        get "produits", to: "espace_pro#produits"
        get "faq",to:"espace_pro#faq"
        get :institut, to: "espace_pro#institut_show", path: "/etablissements/:id"
        get :edit_institut, to: "espace_pro#edit_institut", path: "/etablissements/:id/edit"
        patch :update_institut, to: "espace_pro#update_institut"
        get "delete_photo", to: "espace_pro#delete_photo"
        get "delete_promo", to: "espace_pro#delete_promo"
        get "soins",to:"espace_pro#soins"
      end
    end

    resources :profiles

    resources :blog_posts, only: [:index,:show], path:"blog"

    resources :products, path: "cosmetiques" do
      member do
        get "delete_photo"
      end
      collection do
        #get "/filtres", to: "products#filtres",as: :cosmetique_filtres
        get "click-and-collect",to: "products#click_and_collect", as: :click_collect
        get :besoin, to: "products#type_besoin", path: "/preoccupation/:besoin"
        get :type_product, to: "products#type_product", path: "/type-produit/:type_product"
      end
    end
    #get "/corps", to: "products#category", as: :cosmetique_corps
    resources :soins do
      collection do
        get :visage
        get :corps
        get :massages
        get "cat_bis", to: "soins#cat_bis"
        get :reserver, to: "soins#reservation", path: "/reserver/:soin"
      end
    end
    post "soins/filter", to: "soins#filter"


    scope '/admin' do
      resources :team_members
      resources :prospects
      resources :courses, only: [:new,:create,:edit,:update,:destroy]
      resources :blog_posts, only: [:new,:create,:edit,:update,:destroy]
      get :all_posts, to: "admin#all_posts"
      resources :chapters, only: [:new,:create,:edit,:update,:destroy]
      get "/soins", to: "admin#admin_soins", as: :admin_soins
      get :clients, to: "admin#customers", path: "/clients"
      get :client, to: "admin#customer", path: "/clients/:id"
      get "/tous-les-cours", to: "admin#cours"
      get :instituts, to: "admin#instituts", as: :admin_instituts
      get :preview, to: "courses#preview", path: "/courses/:id/preview"
      get :edit_home_content, to: "admin#edit_home_content"
      post :update_home_content, to: "admin#update_home_content"

      get 'mediatheque', to: "phototheque_espace_pros#index"
      get 'mediatheque/add_file', to: "phototheque_espace_pros#add_file"
      patch 'mediatheque/save_file', to: "phototheque_espace_pros#save_file"
      get :delete_file, to: "phototheque_espace_pros#delete_file", path: "mediatheque/:id/delete"

      resources :phototheque_espace_pro_folders, only: [:new,:create,:show,:edit,:update,:destroy],path: "mediatheque/folders"
      get :mediateque_folder_add_file, to: "phototheque_espace_pro_folders#add_file", path: 'mediatheque/folders/:id/add_file'
      patch 'mediatheque/folders/:id/save_file', to: "phototheque_espace_pro_folders#save_file"
      get :mediateque_folder_delete_file, to: "phototheque_espace_pro_folders#delete_file", path: "mediatheque/folders/:id/delete"
      resources :slider_homes, only: [:index] do
        resources :slide_items, only: [:new,:create,:edit,:update,:destroy]
      end

    end

    resources :admin

    resources :crm do
      collection do
        get :prospects, to: 'crm#crm_prospects', path: ":id/prospects"
        get :show_prospect, :path => "show", path: "prospect/:id"
        get :new_prospect,to: 'crm#new_prospect', :path => "/new"
        get :edit_prospect, :path => "prospect/:id/edit"
        get :clients, to: "crm#crm_customers", path: ":id/clients"
        get :customer, to: "crm#show_customer", path: "/client/:id"
        get :new_customer, to: "crm#new_customer"
        get :edit_customer, to: "crm#edit_customer", path: "/client/:id/edit"

        get :instituts, to: "crm#instituts", path: "instituts"
        get :new_institut, to: "crm#new_institut"
        get :edit_institut, to: "crm#edit_institut", path: "instituts/:id/edit"
        post :create_institut, to: "crm#create_institut"

        get "delete_photo", to: "crm#delete_photo"
        get :statistiques, to: "crm#statistiques", path: ":id/statistiques"

        get :filter_up, to: "crm#filter_up"
        get :filter_down, to: "crm#filter_down"

        post :create_customer, to: "crm#create_customer"
        post :create_prospect, to: "crm#create_prospect"

        get :prospection, to: "crm#prospection"
        get :request_prospection, to: "crm#request_prospection"

        resources :orders

      end
      member do
        patch :update_prospect
        patch :update_customer, to: "crm#update_customer"
        patch :update_institut, to: "crm#update_institut"

        #get :prospects, to: 'crm#crm_prospects'
        #get :edit_prospect, :path => "edit"
        #patch :update_prospect
        #get :show_prospect, :path => "show"
        #get :clients, to: "crm#crm_customers"
        #get :new_customer, to: "crm#new_customer"
        #post :create_customer, to: "crm#create_customer"
        #get :new_institut, to: "crm#new_institut"
        ##get "/client", to: "crm#show_customer"
      end
    end




    resources :instituts, path:"instituts-beaute" do
      collection do
        get :send_contact, path:"send"
        get "/:region/:lieu", to: "instituts#lieu", as: :ville
        get "/villes",to: "instituts#villes", as: :all_villes
      end
    end

    get "/:category", to: "products#categories", as: :cosmetique_category
    post "/:category/filter", to: "products#filter", as: :filter_category

    #get "instituts-beaute/:region/:lieu", to: "instituts#lieu", as: :ville

  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many_attached :photos
  has_many :product_soin_items
  has_many :soins, through: :product_soin_items
  has_many :order_products
  has_many :orders, through: :order_products
  monetize :price_ht_cents

  extend FriendlyId
  friendly_id :name, use: :slugged

  PREOCCUPATIONS = ["hydratation","nutrition","ride","fermeté","nettoyage","imperfection","sensibilité","tiraillement","éclat","minceur"]
  TYPES_PRODUIT = ["crème","sérum","contour des yeux","masque","gommage","nettoyant","lotion","huile"]

  scope :creme, -> { where("'crème' = ANY (types_produit)") }
  scope :serum, -> { where("'sérum' = ANY (types_produit)") }
  scope :contour, -> { where("'contour des yeux' = ANY (types_produit)") }
  scope :masque, -> { where("'masque' = ANY (types_produit)") }
  scope :gommage, -> { where("'gommage' = ANY (types_produit)") }
  scope :nettoyant, -> { where("'nettoyant' = ANY (types_produit)") }
  #serialize :actions, Array
  #serialize :labels, Array
  #serialize :types_peau, Array
  #serialize :contenances, Array
  #serialize :ingredients, Array
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<h1>FORM</h1>
<div class="custom-form">
  <%= simple_form_for @product do |f| %>
    <%= f.input :name %>
    <%= f.input :public %>
    <%= f.input :actions_product, as: :check_boxes, collection: ["PURIFIE", "CICATRISE", "ÉQUILIBRE"] %>
    <%= f.input :description %>
    <%= f.input :gamme, collection: ["visage","corps","soin"] %>
    <%= f.input :preoccupations, as: :check_boxes ,collection: Product::PREOCCUPATIONS %>
    <%= f.input :types_produit, as: :check_boxes ,collection: Product::TYPES_PRODUIT %>
    <%= f.input :labels, as: :check_boxes, collection: ["ECOCERT", "Qualité Nature is Future", "FABRIQUÉ EN FRANCE","NATUREL","PHYTOTHÉRAPIE INNOVANTE"] %>
    <%= f.input :types_peau, as: :check_boxes, collection: ["Toutes peaux","Peau claire"] %>
    <%= f.input :texture %>
    <%= f.input :utilisation %>
    <%= f.input :contenance_revente %>
    <%= f.input :contenance_cabine %>
    <%= f.input :yuka_appreciation , collection: ["Excellent","Bon","Médiocre","Mauvais"]%>
    <%= f.input :product_plus %>
    <%= f.input :product_conseil %>
    <%= f.input :product_gestes %>
    <%= f.input :product_actifs , as: :check_boxes, collection: @actifs%>
    <%= f.input :ingredients, as: :check_boxes, collection: @ingredients %>
    <%= f.input :products_complementaires, as: :check_boxes, collection: Product.all %>
    <div class="form-photos-manage">
      <h3>Photos</h3>
      <div class="list-photos-form">
        <% @product.photos.each do |photo| %>
          <div>
            <%= image_tag photo,height: 100, width: 100, crop: :fill %>
            <%= link_to delete_photo_product_path(product: @product, photo:photo) do %>
              <i class="fa-sharp fa-solid fa-xmark fa-lg"></i>
            <% end%>
          </div>
        <% end %>
      </div>

      <% @product.photos.each do |image| %>
        <%= f.hidden_field :photos, multiple: true, value: image.signed_id %>
      <% end %>

      <%= f.file_field :photos, multiple: true %>
    </div>

    <%= f.submit "Sauvegarder"%>
  <% end %>
</div>

app/views/products/_liste.html.erb
<ul>
  <% products.each do |product| %>
    <%= link_to product_path(product) do %>
       <li class="list_card">
        <div class="image">

          <% if product.photos.attached? %>
            <%= image_tag product.photos[0] %>
          <% else %>
            <%= image_tag('https://res.cloudinary.com/dgznjnwgw/image/upload/v1706693201/static%20files/image-not-available_tmxyvm.jpg') %>
          <% end %>
        </div>
        <h2 class="list_card_name"><%= product.name %></h2>
       </li>
    <% end %>
  <% end %>
</ul>
<!--
<% products.each do |product| %>
  <li><%= link_to product.name, product_path(product) %>|<%= product.types_produit %> | <%= product.preoccupations %></li>
<% end %>
-->

app/views/products/categories.html.erb
<section class="inside categorie-chapo">
  <div id="cover-categorie">
    <%= image_tag @cover %>
  </div>
  <div class="titre-categorie">
    <h1>Nos produits <%= params["category"] %></h1>
    <p><%= @intro %></p>
  </div>
</section>


<div class="inside" id="list_produits_categorie" data-controller="product">
  <aside class="category_form">
    <%= simple_form_for :filtrage, data: {product_target:"form",action:"submit->product#send"},url: filter_category_path(@category), method: :post do |f| %>
      <span class="titre_filtre"><p>Types de produit</p></span>
      <%= f.fields_for :produits_types do |options_form| %>
        <%= options_form.input :crème, as: :boolean, checked_value: 'positive', unchecked_value: 'negative' %>
        <%= options_form.input :sérum, as: :boolean, checked_value: 'positive', unchecked_value: 'negative' %>
        <%= options_form.input :contour_des_yeux, as: :boolean, checked_value: 'positive', unchecked_value: 'negative',label:"Contour des yeux" %>
        <%= options_form.input :masque, as: :boolean, checked_value: 'positive', unchecked_value: 'negative' %>
        <%= options_form.input :gommage, as: :boolean, checked_value: 'positive', unchecked_value: 'negative' %>
        <%= options_form.input :nettoyant, as: :boolean, checked_value: 'positive', unchecked_value: 'negative' %>
      <% end %>
      <span class="titre_filtre"><p>Types de besoin</p></span>
      <%= f.fields_for :besoins_types do |nest_input| %>
        <%= nest_input.input :hydratation, as: :boolean, checked_value: 'positive', unchecked_value: 'negative' %>
        <%= nest_input.input :nutrition, as: :boolean, checked_value: 'positive', unchecked_value: 'negative' %>
        <%= nest_input.input :ride, as: :boolean, checked_value: 'positive', unchecked_value: 'negative' %>
        <%= nest_input.input :fermeté, as: :boolean, checked_value: 'positive', unchecked_value: 'negative' %>
        <%= nest_input.input :nettoyage, as: :boolean, checked_value: 'positive', unchecked_value: 'negative' %>
        <%= nest_input.input :imperfection, as: :boolean, checked_value: 'positive', unchecked_value: 'negative' %>
      <% end %>
      <%= f.hidden_field :category, value: @category %>
      <%= f.submit "Filtrer", class: "btn-rond" %>
    <% end %>

  </aside>
  <section data-product-target="items">
    <%= render partial: "liste", locals: {products: @products} %>
  </section>
</div>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>
<%= render "form", product: @product %>

app/views/products/filter.html.erb
<h1>Filter</h1>

app/views/products/filtres.html.erb
<h1>Filtres</h1>

app/views/products/index.html.erb
<section class="inside categorie-chapo">
  <div id="cover-categorie">
    <%= image_tag "" %>
  </div>
  <div class="titre-categorie">
    <h1>Nos produits <%= params["category"] %></h1>
    <p><%= @intro %></p>
  </div>
</section>


<div class="inside" id="list_produits_categorie" data-controller="product">
  <aside class="category_form">


  </aside>
  <section data-product-target="items">
    <%= render partial: "liste", locals: {products: @products} %>
  </section>
</div>

app/views/products/product_type.html.erb
<h1>Product Type</h1>
#product_type_products

app/views/products/show.html.erb
<article id="product-main">
  <!-- Photo + Elements principaux-->
  <section id="product-first-element" data-controller="product">
    <div class="product-photos">
      <div class="product-photo" data-product-target="imgcover">
        <% @product.photos.each do |photo| %>
          <%= image_tag photo,height: 400, width: 400, class:"pdt-img-main" %>
        <% end %>
      </div>
      <div class="product-carroussel" data-product-target="imgselect">
        <% if @product.photos.attached? %>
          <% @product.photos.each do |photo| %>
            <%= image_tag photo,height: 100, width: 100, class:"pdt-img-select", data: {action: "click->product#carrouselSelect"} %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="product-informations">
      <h1 class="product-name"><%= @product.name %></h1>
      <p class="product-gamme">Gamme <%= @product.gamme %></p>
      <ul class="product-actions">
        <% @product.actions_product.each do |action| %>
          <li><p><%= action %></p></li>
        <% end %>
      </ul>
      <div class="product-description">
        <h2>Description</h2>
        <p class="pdt-desc"><%= @product.description %></p>
      </div>
      <div class="product-labels">
        <ul class="grid five labels">
          <% @product.labels.each do |label| %>
              <li class="product-label">
                <% logo =  @labels[:"#{label}"] %>
                <%= image_tag ("pictos/#{logo}") if !logo.nil? %>
              </li>
          <% end %>
        </ul>
      </div>
      <!-- Peaux texture yuka utilisation -->
      <div class="micro-informations flex">
        <div>
          <div class="flex space-bottom"><h2>Type de peau</h2>
            <p> : </p>
            <% @product.types_peau.each do |peau| %>
              <p><%= peau %></p>
            <% end %>
          </div>
          <div class="flex space-bottom"><h2>Texture</h2><p>: </p><p><%= @product.texture %></p></div>
          <div class="flex space-bottom"><h2>Utilisation</h2><p>: </p><p><%= @product.utilisation %></p></div>
          <div class="contenances space-bottom">
            <h2>Contenances disponibles</h2>
            <ul class="flex">
              <li><span><%= @product.contenance_revente %>ML</span> <span class="contenance-text">format revente</span></li>
              <li><span><%= @product.contenance_cabine %>ML</span> <span class="contenance-text">format cabine</span></li>

            </ul>
          </div>
        </div>
        <div class="avis-product">
          <div class="yuka-picto"><%= image_tag("pictos/yuka.png",class:"picto yuka") %><p><span style="color:<%=@yukacolor %>"><%= @product.yuka_appreciation %> </span>sur Yuka</p></div>
          <p>AVIS<br>Nombre d'avis</p>
        </div>
      </div>
      <!-- Fin Peaux texture yuka utilisation -->
      <div class="product-cta">
        <%= link_to "Approvisionner mon institut","", class:"btn-carre black" %>
        <div class="flex">
          <%= link_to "Le trouver en institut",click_collect_products_path(pdt:@product), class:"btn-carre" %>
          <%= link_to "E-shop","", class:"btn-carre" %>
        </div>
      </div>
    </div>
  </section>
  <!-- Fin Photo + Elements principaux-->
  <section>
    <ul class="accordions" data-controller="accordion">
      <li data-action="click->accordion#toggleAccordion">
        <div><h2>Les + pdts</h2> <%= image_tag("pictos/chevron_bas.svg", class:"picto-chevron") %></div>
        <div class="accordion-hidden" data-accordion-target="content"><p><%= @product.product_plus %></p></div>
      </li>
      <li data-action="click->accordion#toggleAccordion">
        <div><h2>Les conseils</h2> <%= image_tag("pictos/chevron_bas.svg", class:"picto-chevron") %></div>
        <div class="accordion-hidden" data-accordion-target="content"><p><%= @product.product_conseil %></p></div>
      </li>
      <li data-action="click->accordion#toggleAccordion">
        <div><h2>Gestuelle</h2> <%= image_tag("pictos/chevron_bas.svg", class:"picto-chevron") %></div>
        <div class="accordion-hidden" data-accordion-target="content"><p><%= @product.product_gestes %></p></div>
      </li>
      <li data-action="click->accordion#toggleAccordion">
        <div><h2>Ingrédients</h2> <%= image_tag("pictos/chevron_bas.svg", class:"picto-chevron") %></div>
        <div class="accordion-hidden" data-accordion-target="content">
          <p><%= @product.ingredients.join(', ') %></p>
          <% actifs = [] %>
          <% @caroussel_actifs.each do |actif| %>
            <% actifs << actif[:name] %>
          <% end %>
          <p><%= actifs.join(', ')%></p>
        </div>
      </li>
    </ul>
  </section>

  <section class="product-last">
    <h2 class="center">NOS SOINS INCLUANT LE PRODUIT</h2>
   <%= render "shared/carousel", locals:{elements:@soins_associes} %>
  </section>

  <section class="product-last">
    <h2 class="center">PRODUITS COMPLÉMENTAIRES</h2>
    <%= render "shared/carousel", locals:{elements:@products_complementaires} %>
  </section>

</article>

app/views/products/type_besoin.html.erb
<section class="inside categorie-chapo">
  <div id="cover-categorie">
    <%= image_tag "" %>
  </div>
  <div class="titre-categorie">
    <h1>Nos produits pour <%= @besoin %></h1>
    <p><%= @intro %></p>
  </div>
</section>


<div class="inside" id="list_produits_categorie" data-controller="product">
  <aside class="category_form">


  </aside>
  <section data-product-target="items">
    <%= render partial: "liste", locals: {products: @products} %>
  </section>
</div>

app/views/products/type_product.html.erb
<section class="inside categorie-chapo">
  <div id="cover-categorie">
    <%= image_tag "" %>
  </div>
  <div class="titre-categorie">
    <h1>Nos <%= @type_produit %> <%= params["category"] %></h1>
    <p><%= @intro %></p>
  </div>
</section>


<div class="inside" id="list_produits_categorie" data-controller="product">
  <aside class="category_form">


  </aside>
  <section data-product-target="items">
    <%= render partial: "liste", locals: {products: @products} %>
  </section>
</div>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>